# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 05:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Counties',
            },
        ),
        migrations.CreateModel(
            name='Elevenkvmvlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=254)),
                ('internalel', models.FloatField()),
                ('controlcen', models.CharField(max_length=100)),
                ('primarysub', models.CharField(max_length=100)),
                ('primaryfee', models.CharField(max_length=100)),
                ('feederleng', models.FloatField()),
                ('typeofsect', models.CharField(max_length=50)),
                ('linevoltag', models.CharField(max_length=50)),
                ('numberofph', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Elevenkvmvlines',
            },
        ),
        migrations.CreateModel(
            name='Generationplants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('capacity', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Generationplants',
            },
        ),
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Incidences',
            },
        ),
        migrations.CreateModel(
            name='Primarysubstations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=254)),
                ('internalpr', models.FloatField()),
                ('primarysub', models.CharField(max_length=254)),
                ('ownership', models.CharField(max_length=50)),
                ('physicallo', models.CharField(max_length=100)),
                ('incomingvo', models.CharField(max_length=50)),
                ('outgoingvo', models.CharField(max_length=50)),
                ('plotnumber', models.CharField(max_length=50)),
                ('manned', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Primarysubstations',
            },
        ),
        migrations.CreateModel(
            name='Secondarysubstations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('substation', models.CharField(max_length=50)),
                ('primaryfee', models.CharField(max_length=100)),
                ('primaysubs', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=254)),
                ('internalsb', models.FloatField()),
                ('customerss', models.FloatField()),
                ('physicallo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': ' Secondarysubstations',
            },
        ),
        migrations.CreateModel(
            name='Thirtythreekvmvlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryfee', models.CharField(max_length=100)),
                ('primarysub', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=254)),
                ('internaltt', models.FloatField()),
                ('typeofsect', models.CharField(max_length=100)),
                ('feederleng', models.FloatField()),
                ('numberofph', models.CharField(max_length=100)),
                ('linevoltag', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Thirtythreekvmvlines',
            },
        ),
        migrations.CreateModel(
            name='Transmissionlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfeede', models.CharField(max_length=100)),
                ('transsubta', models.CharField(max_length=100)),
                ('internaltl', models.FloatField()),
                ('county', models.CharField(max_length=254)),
                ('typeofsect', models.CharField(max_length=100)),
                ('feederleng', models.CharField(max_length=50)),
                ('linevoltag', models.CharField(max_length=50)),
                ('numberofph', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Transmissionlines',
            },
        ),
        migrations.CreateModel(
            name='Transmissionsubstations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('incomingfe', models.CharField(max_length=10)),
                ('outgoingfe', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=254)),
                ('internaltb', models.FloatField()),
                ('ownership', models.CharField(max_length=50)),
                ('physicallo', models.CharField(max_length=50)),
                ('plotnumber', models.CharField(max_length=50)),
                ('manned', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Transmissionsubstations',
            },
        ),
    ]
