# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_auto_20180623_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevenkvmvlines',
            old_name='internalel',
            new_name='internalpf',
        ),
        migrations.RenameField(
            model_name='primarysubstations',
            old_name='internalpr',
            new_name='internalps',
        ),
        migrations.RenameField(
            model_name='thirtythreekvmvlines',
            old_name='internaltt',
            new_name='internalpf',
        ),
    ]
