# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0005_generationplants_internalgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissionsubstations',
            name='internalgp',
            field=models.FloatField(null=True),
        ),
    ]
