# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0007_auto_20180623_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevenkvmvlines',
            name='internalps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='primarysubstations',
            name='internaltl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='primarysubstations',
            name='transfeede',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secondarysubstations',
            name='internalpf',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='thirtythreekvmvlines',
            name='internalps',
            field=models.FloatField(null=True),
        ),
    ]
